---
javascript:
  all:
    - context
    - context
    - mongodb
    - menu
    - jquery
    - jquery.dialog
    - jquery.selection
    - jquery.commandInput
    - jquery.inputHistory
    - jquery.resultGrid
    - jquery.pager
    - console
    - executor
    - renderer
css:
  all:
    - main
    - console
    - dialog