#only allow local connection
localonly: true

#auto connect to the specified mongo instance
#currently the only way to specify a username/password
auto_connect: mongodb://heroku:PASSWORD@flame.mongohq.com:27071/DATABASE

#list of databases to return. You must set this to your databases
#if you don't have permission to list the databases
databases: [DATABASE1, DATABASE2]